### ISSUE TITLE
Scan Error

### ISSUE THREAD

**Issue by ptilotta** [aliakseiz/go-mysqldump#1]
Hi

I have this error running this library

`Error dumping: template: mysqldumpTable:9:3: executing "mysqldumpTable" at <.CreateSQL>: error calling CreateSQL: sql: expected 4 destination arguments in Scan, not 2
template: mysqldumpTable:9:3: executing "mysqldumpTable" at <.CreateSQL>: error calling CreateSQL: sql: expected 4 destination arguments in Scan, not 2`

I have over 700 lines in the dump file created, but in one table throws this error

the 'TABLE' is already a 'VIEW'

Regards

**Comment by aliakseiz** [comment]
@ptilotta can you share a sample SQL to reproduce the problem?

**Comment by aliakseiz** [comment]
@ptilotta reported issue is fixed in [v1.1.0](https://github.com/aliakseiz/go-mysqldump/releases/tag/v1.1.0).
